sudo: required
services:
    - docker

before_install:
    - docker build -t singhabhinav/react-project -f Dockerfile_dev .

script:
    - docker run -e CI=true singhabhinav/react-project npm run test

deploy:
    provider: elasticbeanstalk
    region: us-west-1                  # Specify your region
    app: "react-project-docker"        # Copy it from Elastic Beanstalk dashboard
    env: "ReactProjectDocker-env"      # Copy it from Elastic Beanstalk dashboard
    bucket_name: "elasticbeanstalk-us-west-1-515682154888"
    bucket_path: "docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master                 # once the changes done in master then only deploy in elastic beanstalk
